site_name: GeoBlacklight Admin User Guide
theme:
  name: material
  palette:
    primary: blue grey
  features:
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
- Home: 'index.md'
- Layout: 'layout.md'
- Create a record: 'create.md'
- Import records: 'import.md'
- Select records: 'select.md'
- Admin Tools: 'admin-tools.md'